#!/usr/bin/env bash

script_dir=$(dirname $(realpath $0))

exitcode=0

for test in $(find $script_dir -name '*.scm')
do
    echo $test
    $script_dir/../pscheme0.sh $@ $test
    if [[ $? -ne 0 ]]; then
        exitcode=1
    else
        ./a.out
        if [[ $? -ne 0 ]]; then
            exitcode=1
        fi
    fi
done
rm -f a.out

if [[ $exitcode == 0 ]]; then
    echo -e "overall: \x1b[1;32mPASS\x1b[0m"
else
    echo -e "overall: \x1b[1;31mFAIL\x1b[0m"
fi

exit $exitcode
